# java bulid
name: Java CI
on: 
  - workflow_dispatch
  - push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: check release version
          id: check_release_version
          run: ${{ env.RELEASE_VERSION }}
        - name: Checkout code
          uses: actions/checkout@v2
    
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
        - name: Build project
          run: mvn package
        - name: Build docker image
          run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/first-java-app:latest .
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: push docker image to docker hub
          run: |
            docker tag ${{ vars.DOCKERHUB_USERNAME }}/first-java-app:latest ${{ vars.DOCKERHUB_USERNAME }}/first-java-app:${{github.ref_type}}
            docker push ${{ vars.DOCKERHUB_USERNAME }}/first-java-app:latest
            docker push ${{ vars.DOCKERHUB_USERNAME }}/first-java-app:${{ github.ref_type }}
        