# java bulid
name: Java CI
on: 
  - workflow_dispatch
  - push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: check java version
          run: java -version
        - name: Checkout code
          uses: actions/checkout@v2
    
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
        - name: Run tests
          run: mvn test & compile 
        - name: Build docker image
          run: docker build -t first-java-app:latest .
        - name: list docker images
          run: docker images
        