# java bulid
name: Java CI
on: 
  - workflow_dispatch
  - push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: check java version
          run: java -version
        - name: Checkout code
          uses: actions/checkout@v2
    
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
        - name: Run tests 
          run: mvn test
        - name: Build project
          run: mvn package
        - name: check targer directory
          run: ls -l target
        - name: Build docker image
          run: docker build -t gowthamarumugam/first-java-app:latest .
        - name: list docker images
          run: docker images
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
           username: ${{ vars.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: push docker image to docker hub
          run: docker push gowthamarumugam/first-java-app:latest
        