# java bulid
name: Java CI
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: check java version
          run: java -version
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Set up JDK 21
          uses: actions/setup-java@v2
          with:
                java-version: '21'
                distribution: 'temurin'
                cache: 'maven'
        - name: Run tests
          run: mvn test
        